services:
  whoami:
    image: traefik/whoami
    command:
       - --name=whoami
    env_file:
      - ./.env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"  

        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_NAME}`)"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE_NAME}.tls=true"
        
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"

        - "traefik.constraint=proxy-public"
    restart: unless-stopped

networks:
  traefik:
    name: homelab_traefik
    external: true