networks:
  traefik-network:
    external: true
  gitea-net:
    driver: bridge

services:
  db:
    image: postgres:${PG_IMAGE_TAG}
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gitea-net

  gitea:
    image: gitea/gitea:${GITEA_IMAGE_TAG}
    container_name: gitea
    restart: always
    depends_on:
      - db
    environment:
      - USER_UID=${GITEA_UID:-110}
      - USER_GID=${GITEA_GID:-111}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${PG_DB_NAME}
      - GITEA__database__USER=${PG_DB_USER}
      - GITEA__database__PASSWD=${PG_DB_PASSWORD}
    volumes:
      - ./gitea-data:/data:rw
    ports:
      - "4345:3000"
    networks:
      - gitea-net
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=cloudflare
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=${GITEA_PORT:-3000}