networks:
  cftunnel-transport:
  traefik-network:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:${CF_IMAGE_TAG}
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
      - TZ=${CF_TZ}
    networks:
      - cftunnel-transport

  traefik:
    image: traefik:${TRAEFIK_IMAGE_TAG}
    # Enables the web UI and tells Traefik to listen to docker
    container_name: traefik
    # command: --api.insecure=true --providers.docker
    command:
      - --certificatesresolvers.cloudflare.acme.email=${TRAEFIK_ACME_EMAIL}
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    volumes:
      # So that Traefik can listen to the Docker events
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/acme.json:/acme.json:rw
    restart: unless-stopped
    networks:
      - traefik-network
      - cftunnel-transport