networks:
  traefik-network:
    external: true
  authentik-net:
    internal: true

volumes:
  postgres-data:
  redis-data:
  authentik-media:
  authentik-templates:
  authentik-certs:

services:
  db:
    image: postgres:${PG_IMAGE_TAG}
    container_name: authentik-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    networks:
      - authentik-net

  redis:
    image: redis:${REDIS_IMAGE_TAG}
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-data:/data
    networks:
      - authentik-net

  authentik:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_IMAGE_TAG}
    container_name: authentik
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=db
      - AUTHENTIK_POSTGRESQL__USER=${PG_DB_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_DB_PASSWORD}
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_EMAIL__HOST=${AUTHENTIK_EMAIL__HOST}
      - AUTHENTIK_EMAIL__PORT=${AUTHENTIK_EMAIL__PORT}
      - AUTHENTIK_EMAIL__USERNAME=${AUTHENTIK_EMAIL__USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${AUTHENTIK_EMAIL__PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS=${AUTHENTIK_EMAIL__USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL=${AUTHENTIK_EMAIL__USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT=${AUTHENTIK_EMAIL__TIMEOUT}
      - AUTHENTIK_EMAIL__FROM=${AUTHENTIK_EMAIL__FROM}
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    networks:
      - authentik-net
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.authentik.entrypoints=websecure
      - traefik.http.routers.authentik.tls=true
      - traefik.http.routers.authentik.tls.certresolver=cloudflare
      - traefik.http.routers.authentik.service=authentik
      - traefik.http.services.authentik.loadbalancer.server.port=${AUTHENTIK_PORT:-9000}
      - traefik.docker.network=traefik-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker: 
    image: ghcr.io/goauthentik/server:${AUTHENTIK_IMAGE_TAG}
    container_name: authentik-worker
    command: worker
    restart: unless-stopped
    user: root
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=db
      - AUTHENTIK_POSTGRESQL__USER=${PG_DB_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_DB_PASSWORD}
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_EMAIL__HOST=${AUTHENTIK_EMAIL__HOST}
      - AUTHENTIK_EMAIL__PORT=${AUTHENTIK_EMAIL__PORT}
      - AUTHENTIK_EMAIL__USERNAME=${AUTHENTIK_EMAIL__USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${AUTHENTIK_EMAIL__PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS=${AUTHENTIK_EMAIL__USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL=${AUTHENTIK_EMAIL__USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT=${AUTHENTIK_EMAIL__TIMEOUT}
      - AUTHENTIK_EMAIL__FROM=${AUTHENTIK_EMAIL__FROM}
    volumes:
      - authentik-certs:/certs
      - authentik-media:/media
      - authentik-templates:/templates
    networks:
      - authentik-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy